version: "3.7"

networks:
  skeleton-docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: always
    tty: true
    container_name: skeleton-docker.php
    depends_on:
      - mariadb
    networks:
      - skeleton-docker.network
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/app.dev

  nginx:
    build: ./docker/nginx
    container_name: skeleton-docker.nginx
    restart: always
    tty: true
    depends_on:
      - php
      - mariadb
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - .:/var/www/app.dev
    networks:
      - skeleton-docker.network

  #  mysql:
  #    build: ./docker/mysql
  #    tty: true
  #    restart: always
  #    container_name: skeleton-docker.mysql
  #    networks:
  #      - skeleton-docker.network
  #    ports:
  #      - "3306:3306"
  #    volumes:
  #      - "./docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
  #      - "./docker/mysql/dbdata:/var/lib/mysql"
  #    environment:
  #      - MYSQL_PASSWORD=root
  #      - MYSQL_ROOT_PASSWORD=root
  #      - MYSQL_DATABASE=development

  mariadb:
    image: mariadb
    tty: true
    restart: always
    container_name: skeleton-docker.mariadb
    networks:
      - skeleton-docker.network
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql/config/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro'
      - './docker/mysql/dbdata:/var/lib/mysql'
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=development

  phpmyadmin:
    image: library/phpmyadmin
    container_name: skeleton-docker.phpmyadmin
    tty: true
    networks:
      - skeleton-docker.network
    depends_on:
      - mariadb
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOSTS: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '8080:80'
